app = "kaimonolog"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/public"
  url_prefix = "/"

[deploy]
  release_command = "bin/rails db:migrate && bin/rails db:seed"